# Pre-processing

Preparations to make a dataset ready for intersectional analysis and optimization. This notebook is a work in progress

## Step 1: necessary imports

In [45]:
# data handling/math
import pandas as pd
import numpy as np

# utils
import sys
import os

sys.path.append(os.path.abspath("../utils"))
from config import DATA_PATH
raw_data_path = DATA_PATH / "raw"
processed_data_path = DATA_PATH / "processed"

## AIDS

In [46]:
df_pp = pd.read_csv(processed_data_path / f"6_aids_pp.csv")
# creating age-group category
bins = [0, 18, 34, 50, 65, 80]
labels = ['0-18', '19-34', '35-50', '51-65', '66-80']
df_pp['age_group'] = pd.cut(df_pp['age'], bins=bins, labels=labels, right=True)
df_pp.head(5)

,trt,age,wtkg,hemo,homo,drugs,karnof,oprior,z30,zprior,...,strat,symptom,treat,offtrt,cd40,cd420,cd80,cd820,target,age_group
0,2,48,89.8128,0,0,0,100,0,0,1,...,1,0,1,0,422,477,566,324,0,35-50
1,3,61,49.4424,0,0,0,90,0,1,1,...,3,0,1,0,162,218,392,564,1,51-65
2,3,45,88.4520,0,1,1,90,0,1,1,...,3,0,1,1,326,274,2063,1893,0,35-50
3,3,47,85.2768,0,1,0,100,0,1,1,...,3,0,1,0,287,394,1590,966,0,35-50
4,0,43,66.6792,0,1,0,100,0,1,1,...,3,0,0,0,504,353,870,782,0,35-50

In [47]:
df_pp.to_csv(processed_data_path / f"6_aids_pp.csv", index=False)

## MENTAL

In [36]:
df_pp = pd.read_csv(processed_data_path / f"mental_health_pp.csv")

In [37]:
print(f'Youngest: {df_pp["age"].min()}\nOldest: {df_pp["age"].max()}')
print(df_pp.shape)

Youngest: -1726
Oldest: 99999999999
(1241, 48)

In [38]:
df_pp = df_pp[df_pp['age'].between(16, 110)]
print(f'Youngest: {df_pp["age"].min()}\nOldest: {df_pp["age"].max()}')
print(df_pp.shape)

Youngest: 18
Oldest: 72
(1233, 48)

In [39]:
# creating age-group category
bins = [0, 18, 34, 50, 65, 80]
labels = ['0-18', '19-34', '35-50', '51-65', '66-80']
df_pp['age_group'] = pd.cut(df_pp['age'], bins=bins, labels=labels, right=True)
df_pp.head(5)

,age,self_employed,family_history,target,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,...,continent_europe,continent_north_america,continent_oceania,continent_south_america,leave_don't_know,leave_somewhat_difficult,leave_somewhat_easy,leave_very_difficult,leave_very_easy,age_group
0,46,1,1,0,1,1,1,0,1,0,...,0,1,0,0,0,0,0,0,1,35-50
1,36,1,1,0,1,1,0,0,1,0,...,1,0,0,0,0,0,1,0,0,35-50
2,29,0,1,1,0,1,1,1,0,0,...,0,1,0,0,0,1,0,0,0,19-34
3,31,1,0,0,1,1,0,0,0,0,...,0,1,0,0,0,1,0,0,0,19-34
4,46,0,0,1,1,1,1,1,0,0,...,0,1,0,0,1,0,0,0,0,35-50

In [40]:
df_pp.isna().sum()

age                            0
self_employed                  0
family_history                 0
target                         0
remote_work                    0
tech_company                   0
benefits                       0
care_options                   0
wellness_program               0
seek_help                      0
anonymity                      0
mental_health_consequence      0
phys_health_consequence        0
mental_health_interview        0
phys_health_interview          0
mental_vs_physical             0
obs_consequence                0
work_interfere_missing         0
work_interfere_never           0
work_interfere_often           0
work_interfere_rarely          0
work_interfere_sometimes       0
gender                         0
non_cis                        0
no_employees_1_5               0
no_employees_100_500           0
no_employees_26_100            0
no_employees_500_1000          0
no_employees_6_25              0
no_employees_more_than_1000    0
coworkers_no                   0
coworkers_some_of_them         0
coworkers_yes                  0
supervisor_no                  0
supervisor_some_of_them        0
supervisor_yes                 0
continent_africa               0
continent_asia                 0
continent_eurasia              0
continent_europe               0
continent_north_america        0
continent_oceania              0
continent_south_america        0
leave_don't_know               0
leave_somewhat_difficult       0
leave_somewhat_easy            0
leave_very_difficult           0
leave_very_easy                0
age_group                      0
dtype: int64

In [ ]:
region_map = {
    "europe_or_north_america": [

    ]
}

In [41]:
df_pp.to_csv(processed_data_path / f"mental_health_pp.csv", index=False)